### ISSUE TITLE
Neither the live nor the local version work

### ISSUE THREAD

**Issue by JanetQC** [xiaodongliang/bim360-node.js-issues.api#7]
Login works, but it seems token is getting lost, so it cannot access the hubs and projects correctly. 
Local version: When I login, grant autodesk access, I get redirected to home page it shows I am not logged in.
Live version:  Logging in, it shows I am logged in, but does not load my project tree.

**Comment by xiaodongliang** [comment]
Hi @JanetQC , my sincerer apology! I did not even notice this issue you reported :(  just a few days ago, I seemed not to see this issue :(  Do you still have the problem of login. I have played the demo a couple of times (for the questions that other customers reported). This sample works well with login process. May I know which browser you are using?  Please feel free to ping me at  xiaodong.liang@autodesk.com
again, apology for the late response!
